### ISSUE TITLE
crash on startup with ZAWA mod.

### ISSUE THREAD

**Issue by celittle3** [simibubi/TheMightyArchitect#3]
WARNING: coremods are present:
  ApotheosisCore (Apotheosis-1.12.2-1.8.6.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.52-core.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  RandomPatches (randompatches-1.12.2-1.15.0.2.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.6.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.3.18.0-build.0262.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.10.0-build.0264.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.3.jar)
  LoadingPlugin (Quark-r1.5-144.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 3/26/19 8:14 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Zoo and Wild Animals Mod: Rebuilt (zawa)
Caused by: java.lang.NullPointerException
	at com.simibubi.mightyarchitect.TheMightyArchitect.onEntityConstructing(TheMightyArchitect.java:109)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_739_TheMightyArchitect_onEntityConstructing_EntityConstructing.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.entity.Entity.<init>(Entity.java:218)
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:73)
	at org.zawamod.client.render.tileentity.TileEntityFeederRenderer.<init>(TileEntityFeederRenderer.java:30)
	at org.zawamod.proxy.ClientProxy.registerRenders(ClientProxy.java:90)
	at org.zawamod.ZAWAMain.preInit(ZAWAMain.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by simibubi** [comment]
Thanks for posting the issue, this should be fixed in 0.2.1.
Have a good day!~

**Comment by celittle3** [comment]
Sweet, thanks.
